version: '2.2'

services:
  db:
    container_name: zropbox_db
    image: mysql:8.0
    volumes:
        - mysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_ROOT_HOST=%
    expose:
      - "3306"
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    networks:
      - appnetwork

  backend:
    container_name: zropbox_backend
    image: ghcr.io/zaanposni/zropbox_backend:latest
    depends_on:
        db:
          condition: service_healthy
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_HOST=db
      - META_SERVICE_BASE_URL=${META_SERVICE_BASE_URL}
      - ABSOLUTE_PATH_TO_FILE_UPLOAD=/filehost/
      - JWT_KEY=${JWT_KEY}
    networks:
      - appnetwork
    volumes:
      - filehost:/filehost

  nginx:
    container_name: zropbox_nginx
    image: ghcr.io/zaanposni/zropbox_nginx:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:5620:80"
    networks:
    - appnetwork
