version: '2.2'

volumes:
  mysql:
  filehost:

services:
  db:
    container_name: zropbox_db
    image: mysql:8.0
    volumes:
        - mysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_ROOT_HOST=%
    expose:
      - "3306"
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    networks:
      - appnetwork

  backend:
    build:
      context: backend
    container_name: zropbox_backend
    depends_on:
        db:
          condition: service_healthy
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_HOST=${MYSQL_HOST}
      - META_SERVICE_BASE_URL=${META_SERVICE_BASE_URL}
      - ABSOLUTE_PATH_TO_FILE_UPLOAD=${ABSOLUTE_PATH_TO_FILE_UPLOAD}
      - JWT_KEY=${JWT_KEY}
      - LOGIN_DURATION=${LOGIN_DURATION}
      - PREF_INIT_PASSWORD=${PREF_INIT_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Development
      - ENABLE_CORS=true
    networks:
      - appnetwork
    volumes:
      - filehost:/filehost

  nginx:
    build:
      context: nginx
    container_name: zropbox_nginx
    restart: unless-stopped
    depends_on:
        - db
        - backend
    ports:
      - "127.0.0.1:5620:80"
    networks:
    - appnetwork

networks:
  appnetwork:
    driver: bridge
